### ISSUE TITLE
benchpark setup ... workspace fails with python 3.12

### ISSUE THREAD

**Issue by jdomke** [GoogleCloudPlatform/ramble#514]
### Steps to reproduce

```
export BM='amg2023/openmp'
export SYS='nosite-x86_64'
./bin/benchpark setup ${BM} ${SYS} workspace
```

### Error message

```
~/benchpark|⇒  ./bin/benchpark setup ${BM} ${SYS} workspace


Setting up configs for Ramble workspace /home/domke/benchpark/workspace/amg2023/openmp/nosite-x86_64/workspace/configs
Cloning spack into /home/domke/benchpark/workspace/spack
Cloning ramble into /home/domke/benchpark/workspace/ramble
Traceback (most recent call last):
  File "/home/domke/benchpark/./bin/benchpark", line 537, in <module>
    main()
  File "/home/domke/benchpark/./bin/benchpark", line 56, in main
    actions[args.subcommand](args)
  File "/home/domke/benchpark/./bin/benchpark", line 451, in benchpark_setup_handler
    run_command(f"{ramble_exe} repo add --scope=site {source_dir}/repo")
  File "/home/domke/benchpark/./bin/benchpark", line 272, in run_command
    raise RuntimeError(
RuntimeError: Failed command: /home/domke/benchpark/workspace/ramble/bin/ramble repo add --scope=site /home/domke/benchpark/repo
Output: 
Error: Traceback (most recent call last):
  File "/home/domke/benchpark/workspace/ramble/bin/ramble", line 66, in <module>
    import ramble.main  # noqa
    ^^^^^^^^^^^^^^^^^^
  File "/home/domke/benchpark/workspace/ramble/lib/ramble/ramble/main.py", line 33, in <module>
    import llnl.util.tty as tty
  File "/home/domke/benchpark/workspace/ramble/lib/ramble/llnl/util/tty/__init__.py", line 22, in <module>
    from six.moves import input
ModuleNotFoundError: No module named 'six.moves'
```

### Information on your system

```
~/benchpark|⇒  python3 --version
Python 3.12.0
```

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by linsword13** [comment]
Thank you for reporting the issue! There's a PR under review that aims to address this: https://github.com/GoogleCloudPlatform/ramble/pull/518.
