### ISSUE TITLE
hpcg no longer works

### ISSUE THREAD

**Issue by rfbgo** [GoogleCloudPlatform/ramble#85]
### Steps to reproduce

Try use a workspace that uses hpcg

### Error message

Error:
```
Traceback (most recent call last):
  File "/home/robertbird_google_com/ramble/bin/ramble", line 69, in <module>
    sys.exit(ramble.main.main())
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/main.py", line 847, in main
    return _main(argv)
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/main.py", line 796, in _main
    return finish_parse_and_run(parser, cmd_name, workspace_format_error)
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/main.py", line 830, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/main.py", line 524, in _invoke_command
    return_val = command(parser, args)
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/cmd/workspace.py", line 675, in workspace
    action(args)
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/cmd/workspace.py", line 324, in workspace_setup
    ws.run_pipeline('setup')
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/workspace/workspace.py", line 1321, in run_pipeline
    app_inst.run_phase(phase, self)
  File "/home/robertbird_google_com/ramble/lib/ramble/ramble/application.py", line 200, in run_phase
    phase_func(workspace)
TypeError: _make_experiments() missing 1 required positional argument: 'expander'
```

Cause: recent refactor changed this interface but hpcg was missed in the update (expander is no longer required) 
```
 77     def _make_experiments(self, workspace, expander):
 78         super()._make_experiments(workspace, expander)
 79
 80         input_path = expander.expand_var('{experiment_run_dir}/hpcg.dat')
 81
 82         with open(input_path, 'w+') as f:
 83             f.write('HPCG benchmark input file\n')
 84             f.write('Sandia National Laboratories; University of Tennessee, Knoxville\n')
 85             f.write(expander.expand_var('{matrix_size}\n'))
 86             f.write(expander.expand_var('{iterations}\n'))
```

### Information on your system

* **Ramble:** 0.0.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-zen2

### General information

- [X] I have run `ramble debug report` and reported the version of Ramble/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by rfbgo** [comment]
(for completeness this will also impact other apps which overload `_make_experiments`, such as hpl and lulesh)
